### ISSUE TITLE
Error in rule BR-BT-00145-0100

### ISSUE THREAD

**Issue by cgiehl** [OP-TED/eForms-SDK#384] opened 2023-03-24 13:53 UTC
Rule BR-BT-00145-0100 checks whether the date of the contract (BT-145-Contract) is earlier than the dispatch date of the notice (BT-05(a)-notice). This means that the date of the contract may only be in the past, otherwise the rule strikes. Up to now, however, it was the case that the contract date could only not be in the future, but the contract date and the notice dispatch date could be identical.

Is this the way it should be or is it a mistake?

**Comment by bertrand-lorentz** [comment] 2023-03-29 15:16
Thanks for your feedback.
We are checking whether it was intended to not allow the date of the contract and the dispatch date to be the same day.

**Comment by YvesJo** [comment] 2023-06-19 08:25
Hi,
After review and confirmation, this bug will get fixed in SDK 1.9.
KR

**Closed** 2023-07-07 12:57 UTC
Labels: validation
