### ISSUE TITLE
Vaildation fails if more than 6 digits are entered in field BT-36

### ISSUE THREAD

**Issue by GarrusMD** [OP-TED/eForms-SDK#995] opened 2024-08-14 08:45 UTC
We have noticed that the validation fails with a plain 500 error if 7 or more digits are entered in the BT-36-Lot or BT-36-Part field.

From a technical point of view, it does not seem sensible to enter more than 6 digits here, but this has already happened twice (in production) due to incorrect entries. From our point of view, it would therefore make sense to restrict the input via a pattern. Alternatively, there should at least be a meaningful error message.

**Comment by YvesJo** [comment] 2024-08-14 09:19
Thanks for reporting that concern.
We will discuss this internally to identify the available options.

**Comment by bertrand-lorentz** [comment] 2024-09-16 15:25
The SDK does not impose any limit on the value in the BT-36-Lot or BT-36-Part field.

I was not able to reproduce the problem: validating a notice with the following value for BT-36-Lot did not cause any error:
```XML
<cbc:DurationMeasure unitCode="YEAR">12345678</cbc:DurationMeasure>
```

I was also able to submit this notice for publication in our test environment.

I assume that you got this error after trying to submit a notice via the API of eNotices2. So the error came probably from the eNotices2 application.

A new version of the application was deployed since your message, so the problem might already have been solved.

I'd suggest that you try to reproduce the problem in the Preview environment, and if you get the error, please contact the TED hepdesk (https://enotices2.ted.europa.eu/help/contact), explaining the steps you took and attaching the XML notice that caused the error.

As this does not seem to be an issue with the eForms SDK, I'm closing this.

**Closed by bertrand-lorentz** 2024-09-16 15:25 UTC
Labels: off-topic > contact helpdesk
