### ISSUE TITLE
BT-08 missing in fields.json

### ISSUE THREAD

**Issue by rkottmann** [OP-TED/eForms-SDK#129] opened 2022-10-04 20:06 UTC
I can not find any entry on BT-08 (Organisation Role) in fields.json. However, I can find BT-08 in many translation files.

Is this a bug?

**Comment by bertrand-lorentz** [comment] 2022-10-20 09:44
Thanks for your feedback.

There is no field corresponding to BT-08 "Organisation Role" because of the different approach in the UBL standard compared to the eForms Regulation (same for BT-770 "Organisation Subrole").
For example, in UBL, the buyer is the organisation under "cac:ContractingParty", and the review body is the organisation under "cac:AppealReceiverParty". So there is no XML element that contains a value indicating the role of an organisation.
You can find related information on this topic in the documentation at:
https://docs.ted.europa.eu/eforms/1.2.1/schema/parties.html

BT-08 is present in the "business-term" translation files, as those files include all business terms defined in the eForms Regulation.

So I'm closing this, as it is "as designed".

**Closed by bertrand-lorentz** 2022-10-20 09:44 UTC

**Comment by rkottmann** [comment] 2022-10-20 11:13
Thx for explaning!
