### ISSUE TITLE
Missing code value 'rl-aut' from BuyerLegalType in Schemtron Rule BR-BT-00011-0052

### ISSUE THREAD

**Issue by rkottmann** [OP-TED/eForms-SDK#304] opened 2023-01-19 08:25 UTC
Hi,

in SDK VErsion 1.5 the code `rl-aut` is missing  although it is listed in the respective codelist  https://github.com/OP-TED/eForms-SDK/blob/4717d4fcbd8170fdb37a8d328bc07d878f612427/codelists/buyer-legal-type.gc#L1725.

This might be a bug and leads to false validation.

thx in advance

**Comment by ferrakaop** [comment] 2023-01-19 08:37
rl-aut is a deprecated value in the buyer-legal-type (also eu-int-org)
https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/buyer-legal-type

The SDK has codelists that contain all the values of the EU Vocabularies codelists but the SDK also has the more limited codelists that are used for eForms.

In this case, eforms-buyer-legal-type is what is used for validation for BT-11, without the deprecated values - see https://docs.ted.europa.eu/eforms/latest/reference/code-lists/eforms-buyer-legal-type.html 

Other codelists like country or currency have a similar way of handling values from EU Vocabularies that are not valid for each version of the SDK.

**Comment by ChristianeCPeters** [comment] 2023-01-19 09:30
Understood

**Comment by bertrand-lorentz** [comment] 2023-01-19 09:43
I'm closing this, as it is not a bug.

**Closed by bertrand-lorentz** 2023-01-19 09:43 UTC
Labels: invalid
